## Filtando Arrays


In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])

#selecionando na mascara apenas valores que a divisão tenha como resto == 0
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

In [9]:
pessoas_id = np.array([[1, 18], [2, 21], [3, 27], [4, 26]])

## selecionando maiores de 21 anos - selecionando primeiro a segunda coluna [1]
pessoas_id[:, 1] > 21



array([[ 3, 27],
       [ 4, 26]])

In [12]:
#passando a mascara
mask_maior_21 = pessoas_id[:, 1] > 21

In [11]:
#mostrando os arrays maior de 21
pessoas_id[mask_maior_21]

array([[ 3, 27],
       [ 4, 26]])

In [13]:
#selecionando apenas os indices
np.where(mask_maior_21)

(array([2, 3]),)

In [17]:
#substituindo numeros por 'maior de idade ' se a condição do id for maior que 21

np.where(pessoas_id > 21, 'maior de idade ', pessoas_id)

array([['1', '18'],
       ['2', '21'],
       ['3', 'maior de idade '],
       ['4', 'maior de idade ']], dtype='<U21')

In [15]:
cartela_bingo = np.array([[ 4, 19, 17,  1],
                            [19, 18, 14, 10],
                            [10,  6,  3,  1],
                            [12,  3,  5,  3]])


In [ ]:
#substituindo tudo o que for divisivel por um texto 'div3 em cartela bingo se a condição for verdadeira
np.where(cartela_bingo % 3 == 0, 'div 3', cartela_bingo)

array([['4', '19', '17', '1'],
       ['19', 'div 3', '14', '10'],
       ['10', 'div 3', 'div 3', '1'],
       ['div 3', 'div 3', '5', 'div 3']], dtype='<U21')