# Concatenação 

In [4]:
#criando cartela bingo
import numpy as np


In [25]:
#criando cartela bingo
#numero min = 1 e numero maximo 60, 4 linhas e 4 colunas
cartela_bingo = np.random.randint(1, 60, size=(4, 4))
cartela_bingo

array([[14, 14, 58, 15],
       [38, 46, 11, 29],
       [53, 22, 17, 53],
       [56, 52, 37, 46]], dtype=int32)

In [26]:
#mostrando toda a cartela menos a ultima linha da tabela de bingo
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo1

array([[14, 14, 58, 15],
       [38, 46, 11, 29],
       [53, 22, 17, 53]], dtype=int32)

In [27]:
#mostrando a ultima linha da tabela de bingo que foi excluida anteriormente
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo2

array([[56, 52, 37, 46]], dtype=int32)

In [28]:
#concatenando as duas tabelas 
np.concatenate((cartela_bingo1, cartela_bingo2))

array([[14, 14, 58, 15],
       [38, 46, 11, 29],
       [53, 22, 17, 53],
       [56, 52, 37, 46]], dtype=int32)

In [29]:
#valiodando se a cartela de bingo é igual a tabela concatenada 
cartela_bingo == np.concatenate((cartela_bingo1, cartela_bingo2))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
##Criando exemplo da sala de espera com numeros de senha 
#np.random.randint(1, 40, size=(4, 3))

sala_espera = np.array(([[38, 24,  3, 'Alice'],
                        [ 7,  2, 13, 'Bob'],
                        [30, 14, 37, 'Cris'],
                        [12,  5, 29, 'Luiz']]))

In [32]:
#eliminando Luiz da sala de espera
#selecionando array sala de espera, selecionando a quarta linha(3) e selecionando o eixo x = 0
np.delete(sala_espera, 3, axis=0)

array([['38', '24', '3', 'Alice'],
       ['7', '2', '13', 'Bob'],
       ['30', '14', '37', 'Cris']], dtype='<U21')